---
---

```{r}
library(tidyverse)
theme_set(ggsidekick::theme_sleek())
p <- seq(0, 1, length.out = 200)
prior <- dunif(p, 0, 1) / length(p)
```

```{r}
dat <- c("W", "L")
dat <- ifelse(dat == "W", 1, 0)
toss <- 1

likelihood <- dbinom(sum(dat), size = length(dat), prob = p)
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)

d <- tibble(toss = toss, posterior = posterior, prior = prior)
ggplot(d, aes(x = p, ymax = posterior, ymin = 0)) +
  geom_ribbon(alpha = 0.2, fill = "red") +
  geom_ribbon(aes(x = p, ymax = prior, ymin = 0), alpha = 0.2) +
  coord_cartesian(expand = FALSE, ylim = c(0, 1.03 * max(c(posterior, prior)))) +
  xlab("Proportion water") +
  ylab("Probability density")
prior <- posterior
```

```{r}
post_samples <- sample(p, prob = posterior, size = 2000, replace = TRUE)
```

```{r}
g <- ggplot(tibble(post_samples), aes(post_samples)) + 
  geom_histogram(bins = 30, alpha = 0.5, fill = "blue") +
  coord_cartesian(expand = FALSE)
g
```

```{r}
q <- mean(post_samples)
g + geom_vline(xintercept = q)

q_median <- median(post_samples)
g + geom_vline(xintercept = q) + geom_vline(xintercept = q_median, lty = 2)
```


```{r}
q <- quantile(post_samples, probs = c(0.1, 0.9))
g + geom_vline(xintercept = q)
```

```{r}
q_hpd <- coda::HPDinterval(coda::as.mcmc(post_samples), prob = 0.8)
q_hpd <- as.numeric(q_hpd)
q_hpd
g + geom_vline(xintercept = q) + geom_vline(xintercept = q_hpd, lty = 2)
```

```{r}
sum(post_samples > 0.5) / length(post_samples)
mean(post_samples > 0.5)
g + geom_vline(xintercept = 0.5)
```

```{r}
mean(post_samples > 0.6 & post_samples < 0.8)
g + geom_vline(xintercept = c(0.6, 0.8))
```

```{r}
q <- sort(post_samples)[round(0.2 * length(post_samples))]
g + geom_vline(xintercept = q)
```




# -------------

```{r}
p <- seq(0, 1, length.out = 300)
# -------

# prior <- dunif(p, 0, 1) / length(p)
# prior <- dbinom(2, size = 3, prob = p)
# prior <- dnorm(p, mean = 0.5, sd = 0.25)
prior <- dbeta(p, shape1 = 3, shape2 = 2)
# prior <- dnorm(p, mean = 0.5, sd = 0.25);prior[1:100] <- 0
# prior <- c(1:150, 150:1)

# -------
dat <- c("W", "L", "W", "L", "W", "W")
# -------

dat <- ifelse(dat == "W", 1, 0)
prior <- prior / sum(prior)

likelihood <- dbinom(sum(dat), size = length(dat), prob = p)
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)

d <- tibble(posterior = posterior, prior = prior)
ggplot(d, aes(x = p, ymax = posterior, ymin = 0)) +
  geom_ribbon(alpha = 0.2, fill = "red") +
  geom_ribbon(aes(x = p, ymax = prior, ymin = 0), alpha = 0.2) +
  coord_cartesian(expand = FALSE, ylim = c(0, 1.03 * max(c(posterior, prior)))) +
  xlab("Proportion water") +
  ylab("Probability density")
```

```{r}
# set.seed(7)
dat <- c("L", "W", "W", "W", "W", "W", "L", "W", "W", "L", "W", "W")
length(dat)
dat <- ifelse(dat == "W", 1, 0)
dat <- rbinom(15, 1, 0.71)

N <- 200
# p <- seq(0, 1, length.out = N)
prior <- dunif(p, 0, 1)
# prior <- dbinom(2, size = 3, prob = p)
# prior <- dbinom(7, size = 10, prob = p)
# prior <- dbinom(71, size = 100, prob = p)
# prior <- dbinom(5, size = 10, prob = p)
# prior <- dnorm(p, mean = 0.5, sd = 0.3)
# prior <- dbeta(p, shape1 = 3, shape2 = 2)
# prior <- dnorm(p, mean = 0.5, sd = 0.25);prior[1:100] <- 0

prior <- prior / sum(prior)

out <- list()
for (i in seq_along(dat)) {
  likelihood <- dbinom(sum(dat[i]), size = 1, prob = p)
  posterior <- likelihood * prior
  posterior <- posterior / sum(posterior)
  out[[i]] <- data.frame(p, prior, posterior, toss = i)
  prior <- posterior # for next time
}
out <- bind_rows(out)
rm(prior, posterior, likelihood)

ggplot(out, aes(x = p, ymax = posterior, ymin = 0, group = toss)) +
  geom_ribbon(alpha = 0.1, fill = "blue") +
  geom_ribbon(aes(x = p, ymax = prior, ymin = 0), alpha = 0.08) +
  coord_cartesian(expand = FALSE) +
  xlab("Proportion water") +
  ylab("Probability density")  +
  facet_wrap(~toss) +
  geom_vline(xintercept = 0.71, lty = 2, col = "grey60")
```

