---
title: "Advice, links, and useful resources"
output: html_document
---

# Stan resources

The main documentation:
<http://mc-stan.org/users/documentation/>

Stan Best Practices:
<https://github.com/stan-dev/stan/wiki/Stan-Best-Practices>

Prior Choice Recommendations:
<https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations>

Case studies:
<http://mc-stan.org/users/documentation/case-studies.html>

Tutorials, books, online video courses, and presentations:
<http://mc-stan.org/users/documentation/tutorials.html>

Forums:
<http://discourse.mc-stan.org/>

Examples from many textbooks converted into Stan:
<https://github.com/stan-dev/example-models>

tidybayes:
<https://github.com/mjskay/tidybayes>

Visualize MCMC algorithms including NUTS:
<https://chi-feng.github.io/mcmc-demo/>

Statistical Rethinking Fall 2017 lectures:
<https://youtu.be/oy7Ks3YfbDg>

# Papers

Monnahan, C.C., Thorson, J.T., and Branch, T.A. 2016. Faster estimation of Bayesian models in ecology using Hamiltonian Monte Carlo. Methods Ecol Evol. <https://doi.org/10.1111/2041-210X.12681>.

Gabry, J., Simpson, D., Vehtari, A., Betancourt, M., and Gelman, A. 2019. Visualization in Bayesian workflow. Journal of the Royal Statistical Society Series A: Statistics in Society 182(2): 389–402. <https://doi.org/10.1111/rssa.12378>

Gelman, A., Vehtari, A., Simpson, D., Margossian, C.C., Carpenter, B., Yao, Y., Kennedy, L., Gabry, J., Bürkner, P.-C., and Modrák, M. 2020. Bayesian Workflow. arXiv:2011.01808. <https://arxiv.org/abs/2011.01808>

Vehtari, A., Gelman, A., Simpson, D., Carpenter, B., and Bürkner, P.-C. 2021. Rank-normalization, folding, and localization: an improved $\hat{R}$ for assessing convergence of MCMC (with discussion). Bayesian Analysis 16(2): 667–718. International Society for Bayesian Analysis. <https://arxiv.org/abs/1903.08008>

Vehtari, A., Gelman, A., and Gabry, J. 2017. Practical Bayesian model evaluation using leave-one-out cross-validation and WAIC. Statistics and Computing 27(5): 1413–1432. doi:10.1007/s11222-016-9696-4. <https://arxiv.org/abs/1507.04544>

Vehtari, A., Simpson, D., Gelman, A., Yao, Y., and Gabry, J. 2024, March 13. Pareto Smoothed Importance Sampling. arXiv. doi:10.48550/arXiv.1507.02646. <https://arxiv.org/abs/1507.02646>

Betancourt, M. 2017. A Conceptual Introduction to Hamiltonian Monte Carlo. arXiv:1701.02434 [stat]. <http://arxiv.org/abs/1701.02434>

# Textbooks 

Hobbs, N.T., and Hooten, M.B. 2015. Bayesian models: a statistical primer for ecologists. Princeton University Press, Princeton, New Jersey.

- The best textbook I've found on the fundamentals of Bayesian models from an ecologist's perspective. I've never found another book that filled in so many gaps in understanding. An excellent resource on how to read and write Bayesian models. Note that this textbook does not focus on code. 

McElreath, R. 2020. Statistical rethinking: a Bayesian course with examples in R and Stan. 2nd edition. CRC Press/Taylor & Francis Group.
<https://xcelab.net/rm/statistical-rethinking/>

- A fantastic textbook that will help you think about Bayesian modeling and modeling in general. Perhaps the one downside is that it uses the author's 'rethinking' R package throughout, which is great from pedagogical perspective but not great if you want to learn Stan code itself. Still very much worth it though. Stan code itself is relatively easy to learn once you understand the concepts. And in many cases there's no need to write the code yourself anyways. 
- See this repository that includes most of the examples reworked with the brms package and ggplot2: <https://bookdown.org/content/3890/>

Gelman, A., Hill, J., and Vehtari, A. 2021. Regression and other stories. Cambridge University Press, Cambridge. doi:10.1017/9781139161879.

- An excellent textbook on regression and GLMs in a Bayesian context. Examples are mostly from the social, political, and health sciences, but applicable to anything. Also deals with causal inference.
- Examples and other material here: <https://avehtari.github.io/ROS-Examples/>

Gelman, A., J. B. Carlin, H. S. Stern, D. B. Dunson, A. Vehtari, and D. B. Rubin. 2014. Bayesian Data Analysis. Chapman & Hall, Boca Raton, FL.

- The Bayesian data analysis bible, but definitely not easy reading.

# Not specifically about Bayesian modeling, but still very useful

Schielzeth, H. 2010. Simple means to improve the interpretability of regression coefficients. Methods in Ecology and Evolution 1:103–113.

Gelman, A. 2008. Scaling regression inputs by dividing by two standard deviations. Statistics in Medicine 27:2865–2873.

Morey, R. D., Hoekstra, R., Rouder, J., Lee, M. D., and Wagenmakers, E. (2016). The fallacy of placing confidence in confidence intervals. Psychonomic Bulletin & Review. 23(1), 103–123.
