---
title: MCMC diagnostics
---

For each of the following sets of MCMC chains, answer the following:

1. Are these samples consistent with convergence?
2. What helped you come to that conclusion?

If inconsistent with convergence, continue:

3. What might have caused this scenario?
4. Can the MCMC sampling likely be improved without adjusting the model?
5. If so, what might improve the MCMC sampling?

```{r mcmc-chains1}
samples <- readRDS(here::here("data/mcmc1.rds"))
samples_matrix <- do.call(cbind, samples)

bayesplot::mcmc_trace(samples)
rstan::Rhat(samples_matrix)
rstan::ess_bulk(samples_matrix)
rstan::ess_tail(samples_matrix)
```

```{r mcmc-chains2}
samples <- readRDS(here::here("data/mcmc2.rds"))
samples_matrix <- do.call(cbind, samples)

bayesplot::mcmc_trace(samples)
rstan::Rhat(samples_matrix)
rstan::ess_bulk(samples_matrix)
rstan::ess_tail(samples_matrix)
```

```{r mcmc-chains3}
samples <- readRDS(here::here("data/mcmc3.rds"))
samples_matrix <- do.call(cbind, samples)

bayesplot::mcmc_trace(samples)
rstan::Rhat(samples_matrix)
rstan::ess_bulk(samples_matrix)
rstan::ess_tail(samples_matrix)
```

```{r mcmc-chains4}
samples <- readRDS(here::here("data/mcmc4.rds"))
samples_matrix <- do.call(cbind, samples)

bayesplot::mcmc_trace(samples)
rstan::Rhat(samples_matrix)
rstan::ess_bulk(samples_matrix)
rstan::ess_tail(samples_matrix)
```

```{r mcmc-chains5}
samples <- readRDS(here::here("data/mcmc5.rds"))
samples_matrix <- do.call(cbind, samples)

bayesplot::mcmc_trace(samples)
rstan::Rhat(samples_matrix)
rstan::ess_bulk(samples_matrix)
rstan::ess_tail(samples_matrix)
```

```{r mcmc-chains6}
samples <- readRDS(here::here("data/mcmc6.rds"))
samples_matrix <- do.call(cbind, samples)

bayesplot::mcmc_trace(samples)
rstan::Rhat(samples_matrix)
rstan::ess_bulk(samples_matrix)
rstan::ess_tail(samples_matrix)
```
