---
title: Priors
output:
  html_document:
    toc: true
    toc_float: true
---

how to find what priors are needed in brms and defaults
how to specify specific parameters
see influence of priors
try a prior predictive check (pushforward and new obs)
understand brms's treatment of intercepts

```{r}
library(ggplot2)
library(dplyr)
theme_set(theme_light())
library(brms)
```

```{r}
x <- 1:20
n <- length(x)
a <- 0.2
b <- 0.3
sigma <- 1
set.seed(2141)
y <- a + b * x + sigma * rnorm(n)
fake <- data.frame(x, y)
```

```{r}
ggplot(fake, aes(x, y)) + geom_point()
```

```{r}
brms::default_prior(
  y ~ x, data = fake
)
```

```{r}
mod1 <- brm(y ~ x, data = fake, family = gaussian())
```

```{r}
get_prior(mod1)
```

```{r, eval=FALSE}
mod1 <- brm(y ~ x, data = fake, family = gaussian(),
  prior = c(
    set_prior("normal(0, 1)", class = "Intercept"),
    set_prior("normal(0, 1)", class = "b"),
    set_prior("student_t(3, 0, 3)", class = "sigma")
  ),
  sample_prior = "yes"
)
```

```{r}
mod2 <- brm(y ~ 0 + Intercept + x, data = fake, family = gaussian(),
  prior = c(
    set_prior("normal(0, 1)", class = "b", coef = "Intercept"),
    set_prior("normal(0, 1)", class = "b", coef = "x"),
    set_prior("student_t(3, 0, 3)", class = "sigma")
  ),
  sample_prior = "yes"
)
```

```{r}
stancode(mod1)
stancode(mod2)
```

```{r}
sims1 <- as_draws_df(mod1)
mean(sims1$b_Intercept)
mean(sims1$Intercept)
mean(fake$y)
```

```{r}
sims2 <- as_draws_df(mod2)
mean(sims2$b_Intercept)
mean(fake$y)
```

```{r}
p2 <- brms::prior_draws(mod2) # sample_prior = "yes"
hist(p2$b_x, breaks = 50)
hist(p2$sigma, breaks = 50)
```

```{r}
mod_prior_only <- brm(y ~ 0 + Intercept + x, data = fake, family = gaussian(),
  prior = c(
    set_prior("normal(0, 5)", class = "b", coef = "Intercept"),
    set_prior("normal(0, 1)", class = "b", coef = "x"),
    set_prior("student_t(3, 0, 3)", class = "sigma")
  ),
  sample_prior = "only", #<
  seed = 2028, iter = 100, chains = 1
)
```

```{r}
prior_pushforward <- brms::posterior_epred(mod_prior_only)
prior_predictive <- brms::posterior_predict(mod_prior_only)
```

```{r}
fake$pf1 <- prior_pushforward[1,]
fake$pf2 <- prior_pushforward[2,]
fake$pf3 <- prior_pushforward[3,]
ggplot(fake, aes(x, pf1)) + geom_point()
ggplot(fake, aes(x, pf2)) + geom_point()
ggplot(fake, aes(x, pf3)) + geom_point()
```

```{r}
fake$pp1 <- prior_predictive[1,]
fake$pp2 <- prior_predictive[2,]
fake$pp3 <- prior_predictive[3,]
ggplot(fake, aes(x, pp1)) + geom_point()
ggplot(fake, aes(x, pp2)) + geom_point()
ggplot(fake, aes(x, pp3)) + geom_point()
```

```{r}
mod_prior_only_wide <- brm(y ~ 0 + Intercept + x, data = fake, family = gaussian(),
  prior = c(
    set_prior("normal(0, 100)", class = "b", coef = "Intercept"),
    set_prior("normal(0, 100)", class = "b", coef = "x"),
    set_prior("student_t(3, 0, 100)", class = "sigma")
  ),
  sample_prior = "only",
  seed = 2028, iter = 100, chains = 1
)
```

```{r}
prior_predictive <- brms::posterior_predict(mod_prior_only_wide)
fake$pp1 <- prior_predictive[1,]
fake$pp2 <- prior_predictive[18,]
fake$pp3 <- prior_predictive[42,]
ggplot(fake, aes(x, pp1)) + geom_point()
ggplot(fake, aes(x, pp2)) + geom_point()
ggplot(fake, aes(x, pp3)) + geom_point()
```

```{r}
library(ggplot2)
library(rstanarm)
theme_set(theme_light())

mcmc_example <- function(
  seed = 1,
  intercept = 3,
  slope = 0.7,
  sigma = 2, # the true residual SD
  .n = 30, # number of data points to simulate
  prior_slope_mean = 0,
  prior_slope_sd = 3,
  prior_intercept_sd = 10,
  prior_aux_sd = 3,
  reps = 600 # the length of each MCMC chain
) {

  set.seed(seed)
  x <- arm::rescale(runif(.n, -2, 2))
  d <- data.frame(x = x, y = rnorm(.n, mean = intercept + slope * x, sd = sigma))

  m <- stan_glm(y ~ x, d, iter = reps, chains = 1,
    family = gaussian(link = "identity"), refresh = 0,
    prior = normal(prior_slope_mean, prior_slope_sd, autoscale = FALSE),
    prior_intercept = normal(0, prior_intercept_sd, autoscale = FALSE),
    prior_aux = normal(0, prior_aux_sd, autoscale = FALSE),
    chains = 1, cores = 1
    )

  e <- as.data.frame(m)

  xx <- seq(-6, 6, length.out = 200)

  slope_prior <- data.frame(x = xx,
    y = dnorm(xx, mean = prior_slope_mean, sd = prior_slope_sd))

  intercept_prior <- data.frame(x = xx,
    y = dnorm(xx, mean = 0, sd = prior_intercept_sd))

  xx0 <- seq(0, 6, length.out = 200)
  sigma_prior <-  data.frame(x = xx0,
    y = extraDistr::dhnorm(xx0, sigma = prior_aux_sd))

  .range <- c(-4, 4)

  g1 <- ggplot(e, aes(`(Intercept)`, after_stat(density))) + geom_histogram(bins = 50) +
    geom_line(data = intercept_prior, aes(x, y), col = "blue") +
    coord_cartesian(xlim = .range) +
    xlab("Intercept") +
    geom_vline(xintercept = intercept, col = "red")

  g2 <- ggplot(e, aes(x, after_stat(density))) + geom_histogram(bins = 50) +
    geom_line(data = slope_prior, aes(x, y), col = "blue") +
    coord_cartesian(xlim = .range) +
    xlab("Slope coefficient") +
    geom_vline(xintercept = slope, col = "red")

  g3 <- ggplot(e, aes(sigma, after_stat(density))) + geom_histogram(bins = 50) +
    geom_line(data = sigma_prior, aes(x, y), col = "blue") +
    coord_cartesian(xlim = c(0, max(.range))) +
    xlab("Observation error SD") +
    geom_vline(xintercept = sigma, col = "red")

  nd <- data.frame(x = seq(-1, 1, length.out = 2))
  pp <- posterior_linpred(m, newdata = nd, draws = 50)
  pp2 <- reshape2::melt(pp)
  pp2$x <- rep(nd$x, each = 50)

  g4 <- ggplot(d, aes(x = x, y = y)) +
    geom_point() +
    geom_line(data = pp2, aes(x, value, group = iterations), inherit.aes = FALSE,
      alpha = 0.5, col = "grey30") +
    geom_abline(slope = slope, intercept = intercept,
      col = "red")

  gridExtra::grid.arrange(g1, g2, g3, g4, ncol = 2)
}
```


```{r}
library(manipulate)
manipulate(
  mcmc_example(
    seed = seed,
    intercept = 2.4,
    slope = slope,
    sigma = sigma,
    .n = .n,
    prior_slope_mean = prior_slope_mean,
    prior_slope_sd = prior_slope_sd,
    prior_intercept_sd = prior_intercept_sd,
    prior_aux_sd = prior_aux_sd),
  seed = slider(1, 1000, 42, step = 1),
  # intercept = slider(-5, 5, 0, step = 0.2),
  slope = slider(-1.6, 1.6, 0.8, step = 0.2),
  sigma = slider(0.1, 8, 1, step = 0.1),
  .n = slider(2, 200, 30),
  prior_slope_mean = slider(-5, 5, 0, step = 0.5),
  prior_slope_sd = slider(0.2, 10, 2, step = 0.2),
  prior_intercept_sd = slider(0.2, 20, 10, step = 0.2),
  prior_aux_sd = slider(0.2, 10, 3, step = 0.2)
)
```

